name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Run tests
      run: swift test --enable-test-discovery

    - name: Install Cocoapods
      run: gem install cocoapods

    - name: Lint Podspec
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings --use-libraries
