name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run tests
      run: swift test --enable-test-discovery

    - name: Lint Podspec
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings --use-libraries
    
    - name: Carthage update
      run: ./scripts/carthage.sh update --platform "ios,macos,tvos,watchos"
